import { Router } from 'express';
import facilityRoutes from './facility.routes';
import branchRoutes from './branch.routes';
import departmentRoutes from './department.routes';
import medicalRoomRoutes from './medical-room.routes';
import specialtyRouter from './specialty.route';
import medicalServiceRoutes from './medical-service.routes';
import specialtyServiceRoutes from './specialty-service.routes';
import departmentSpecialtyRoutes from './department-specialty.routes';
import doctorServiceRoutes from './doctor-service.routes';
import medicalEquipmentRoutes from './medical-equipment.routes';
import { bedRoutes } from './bed.routes';
import staffRoutes from './staff.routes';
import shiftRoutes from './shift.routes';
import { slotRoutes } from './appointment-slot.routes';
import { staffScheduleRoutes } from './staff-schedule.routes';
import { leaveRoutes } from './leave.routes';
import { shiftSwapRoutes } from './shift-swap.routes';
import { licenseRoutes } from './license.routes';
import { operatingHourRoutes } from './operating-hour.routes';
import { closedDayRoutes } from './closed-day.routes';
import { holidayRoutes } from './holiday.routes';
import { facilityStatusRoutes } from './facility-status.routes';
import bookingConfigRoutes from './booking-config.routes';
import { roomMaintenanceRoutes } from './room-maintenance.routes';

const router = Router();

router.use('/facilities', facilityRoutes);
router.use('/branches', branchRoutes);
router.use('/departments', departmentRoutes);
router.use('/medical-rooms', medicalRoomRoutes);
router.use('/specialties', specialtyRouter);
router.use('/medical-services', medicalServiceRoutes);
router.use('/specialty-services', specialtyServiceRoutes);
router.use('/department-specialties', departmentSpecialtyRoutes);
router.use('/doctor-services', doctorServiceRoutes);
router.use('/equipments', medicalEquipmentRoutes);
router.use('/beds', bedRoutes);
router.use('/staff', staffRoutes);
router.use('/shifts', shiftRoutes);
router.use('/slots', slotRoutes);
router.use('/staff-schedules', staffScheduleRoutes);
router.use('/leaves', leaveRoutes);
router.use('/shift-swaps', shiftSwapRoutes);
router.use('/licenses', licenseRoutes);
router.use('/operating-hours', operatingHourRoutes);
router.use('/closed-days', closedDayRoutes);
router.use('/holidays', holidayRoutes);
router.use('/facility-status', facilityStatusRoutes);
router.use('/booking-configs', bookingConfigRoutes);
router.use('/room-maintenance', roomMaintenanceRoutes);

export default router;
